DRAFT Feat/ghpc venn diagram
CSIS-iLab/js-viz pull request #119
Opened 2021-11-23 16:01 UTC by KaiElwood

Draft PR request. Do not merge!

2021-11-24 00:15 UTC, jdromero88 requested changes
Hey @KaiElwood. Great job on this parce!! I left you 2 comments.

When you submit the final PR don't forget to remove all the `console.log()`s & to convert all the margins and paddings to `rem`s.

Tip: you can link the PR to an issue in different ways. By doing this when the PR is approved and merged it will close the issue automatically. You can see how to link them [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

2021-12-08 20:01 UTC, KaiElwood commented
Final edits have been made, ready for final review

2021-12-08 20:59 UTC, jdromero88 requested changes
Great job @KaiElwood!!! the diagram looks AMAZING!!
I left you one comment after that let me know and I will merge it.

2021-12-08 20:59 UTC, jdromero88 commented on ghpc-TB-venn-diagram/css/styles.css
> +    text-shadow: 0px 0px 10px #00000040;
For consistency we should remove the px on 0 values.
```suggestion
    text-shadow: 0 0 10px #00000040;
```

2021-12-08 21:11 UTC, merged