Feat/critical minerals
CSIS-iLab/js-viz pull request #123
Opened 2022-01-20 17:18 UTC by KaiElwood

this is the big pr – I'll be making branches off of this in the future.

2022-01-21 00:18 UTC, smaraghi commented on escc-critical-minerals/viz/src/App.svelte
> +// Mock data; Use structure above for production
Go ahead and remove the mock data. It was just to get the templates working.

2022-01-21 00:25 UTC, smaraghi commented on escc-critical-minerals/viz/src/components/Chart.svelte
> +    .domain([0, 75])
It is more true to the data to keep both domains at 100 (100%). Though I see why you cut the x-axis off at 75 as there is not any data that surpasses this point. There could be data in the future that does.

2022-01-21 00:27 UTC, smaraghi commented on escc-critical-minerals/viz/src/components/Chart.svelte
> +  // I don't understand what is happening here with the ; element in svelte
The resize function is multi-lined with a single line with no return thus the semicolon is populated

2022-01-21 00:28 UTC, smaraghi commented on escc-critical-minerals/viz/src/components/Chart.svelte
> +
bind:this is similar to document.getElementByID('figure') >>> essentially we are setting the value of the figure to that element

2022-01-21 00:32 UTC, smaraghi commented on escc-critical-minerals/viz/src/components/Chart.svelte
> +<style>
Add type="text/scss" to your style tag to make sure your SASS import is compiled

2022-01-21 01:09 UTC, smaraghi commented on escc-critical-minerals/viz/src/data.js
> +    let correcteddata = initialdata.map((d) => {
In this function, NaN's from the data are converted to 0. The issue with this is that 0 in the dataset has a meaning and set value (the x or y point of 0). And NaN in the dataset means "Not Available". As we do not have the data for a particular point, we cannot plot it. So our best move is to remove it from the data visualization by using a JavaScript filter and the isNAN function:

 let correcteddata = initialdata.filter((d) => !isNaN(d.production2020) && !isNaN(d.reserves2020))

2022-01-21 01:19 UTC, smaraghi commented on escc-critical-minerals/viz/src/data.js
> +
To prevent issues with types later on, it is important to make sure the keys in your data that need to be strings are strings and need to be numbers are numbers. You can do this in multiple ways such as using the parseInt operator. 

One way that we have set up parsing our strings & numbers in our data is through a stringify function (You would place the following at the top of your data.js):

const stringFields = [
  'country',
  'region',
  'mineral',
]

const stringify = d => {
  for (var i in d) {
    if (!stringFields.includes(i)) {
      d[i] = +d[i]
    }
  }
  return d
}


***You would then need to pass the stringify function into the d3Fetch as a 2nd param so it can modify the data accordingly:

  const scatterPromise = d3Fetch.csv(src.scatter, stringify)
  
  
  _________
  
 What this function does is it takes an array of strings (stringFields) and everything that is not included in that array gets a plus sign added to it which then coerces its value to a number.

2022-01-21 01:50 UTC, smaraghi commented on escc-critical-minerals/viz/src/data.js
> +    let minerals = ['Cobalt', 'Lithium', 'Nickel', 'Rare Earths', 'Manganese', 'Graphite'];
This is a fine solution as we are not planning on updating this data in the future. But if you work with a program in the future where the data may change or new minerals may get added for example, it is best to not hardcode data and pull from the CSV for scalability instead.

2022-01-21 01:55 UTC, smaraghi commented on escc-critical-minerals/viz/src/data.js
> +    let dataset = [{mineral: minerals[0], mineralData: []}, {mineral: minerals[1], mineralData: []}, {mineral: minerals[2], mineralData: []}, {mineral: minerals[3], mineralData: []}, {mineral: minera
As programmers we want to always make sure we are building scalable and dry (non-repetitive) code. The simpler the code, the better it reads and usually functions. A better way to set up your dataset so it aligns with these conventions is to have it map over the set of minerals and create the desired object for each one programmatically:

let dataset = minerals.map((mineral) => {
      return {
        mineral: mineral,
        mineralData: correcteddata.filter(d => d.mineral === mineral),
        totalProduction: 0,
        totalReserves: 0
      }
    })
    
    This object block will also result in cleaning up the following forloops like so:
    
    for(let x = 0; x < minerals.length; x++) {
      dataset[x].mineralData.forEach(d => {
        dataset[x].totalProduction += d.production2020;
        dataset[x].totalReserves += d.reserves2020;
      })
      dataset[x].mineralData.forEach(d => {
        d.percentReserves = ((d.reserves2020 / dataset[x].totalReserves)*100);
        d.percentProduction = ((d.production2020 / dataset[x].totalProduction)*100);
      })
    }
    
    
    You can take the refactor a step further and simplify the forloop block if desired as well.

2022-01-21 01:58 UTC, smaraghi requested changes
Great job Kai! I'm so excited that you are getting to learn Svelte. There are some notes I have left for you to take a look at and changes for you to make within them. If you have any questions - reach out. 

Happy Svelting!

2022-01-26 18:35 UTC, KaiElwood commented on escc-critical-minerals/viz/src/data.js
> +    let correcteddata = initialdata.map((d) => {
this is a little more complicated because it will change the overall percentages for each country – maybe we can talk to Nikos about this first before moving forward?

2022-01-26 18:56 UTC, KaiElwood commented on escc-critical-minerals/viz/src/data.js
> +    let dataset = [{mineral: minerals[0], mineralData: []}, {mineral: minerals[1], mineralData: []}, {mineral: minerals[2], mineralData: []}, {mineral: minerals[3], mineralData: []}, {mineral: minera
this makes a lot of sense!

2022-02-03 18:52 UTC, smaraghi requested changes
Review #2 

1. Chart container grid - Remove column gap. The grid + padding is spacing the columns out just fine. This is adding unnecessary space. Removing this will also help pull the legend into the 800px space 
2. Legend
- Currently the Region bubbles are at R7 make them R5 to match the size of the bubbles on the chart more
- The region legend still expands past 800. Do #1 and see where we are after. If you are still a little outside the chart we may have to use relative positioning 
3. The X Y Axis tiitles are too small. Make them 12px instead of 10. 10 is unreadable on desktop and will be on mobile as well
4. Rearrange your HTML so that the bubbles cover the axis not the other way around 
![image](https://user-images.githubusercontent.com/45780666/152408986-d540b745-a73f-4f45-b480-f9c5204fd03f.png)

5. Add the following to your button styling - this will differentiate from the CPP buttons:
- Border radius: 3px
-   background-color: $button__active-state;
- Adding 4px of padding between the buttons (I'd only add it to the first button because you dont want additional space between the second button and the legend)

6. Instead of 'Group By' - should it be 'Color By' ? What do you think?
7. Animation: Slow it down - maybe turn it up to 800 and see how that feels. It happens so fast after load. It is hard to catch. The second thing - it doesnt happen again once you switch to Regions and it should. Check out Svelte #key to help redraw. I think if you wrap that around your figure or for (I'd have to look deeper) that should help you solve your problem. 
8. Add your source. We need to do this before sending it to them.

2022-03-04 17:25 UTC, smaraghi requested changes
Kai, great job on this!

Please clean up your code before we merge it in:

Place all colors in the SCSS files into your Variables file, remove unnused code (the average line), remove any remaining console logs

Turn your PR from a draft PR to a real one

2022-03-07 19:13 UTC, smaraghi commented on escc-critical-minerals/viz/src/scss/components/_form-elements.scss
> +
Remove commented/unused code

2022-03-07 19:16 UTC, smaraghi requested changes
Great Job Kai! Just a bit more clean up to do. 

Please remove any unused/commented code - I added one single line comment as an example and clean up your code comments. 

Code comments should guides for developers that come after you. 

"If someone were to jump into my codebase - what would they need guidance understanding? What tips or notes would I want to leave behind?"

With this in mind - think about what comments are really necessary to keep in the codebase.

2022-03-07 21:18 UTC, smaraghi commented on escc-critical-minerals/viz/README.md
> +
Update Readme - this is from the previous interactive

2022-03-07 21:19 UTC, smaraghi commented on escc-critical-minerals/viz/package.json
> +    "d3-array": "^2.12.0",
Are you using all of these dependencies? Like d3-array or d3-shape? If not, please remove.

2022-03-07 21:20 UTC, smaraghi commented on escc-critical-minerals/viz/src/App.svelte
> +  import Options from './components/Options.svelte'
Unused/Commented Code: Remove this line

2022-03-07 21:20 UTC, smaraghi commented on escc-critical-minerals/viz/src/App.svelte
> +
Unused/Commented Code: Remove this line

2022-03-07 21:20 UTC, smaraghi commented on escc-critical-minerals/viz/src/App.svelte
> +
Remove console logs when going into production

2022-03-07 21:22 UTC, smaraghi commented on escc-critical-minerals/viz/src/App.svelte
> +
Are you using these variables -> isMobile & mq ?

If not, please remove them and all accompanying functions from the codebase

2022-03-08 15:10 UTC, merged